"""initial schema

Revision ID: db7a04b5fc60
Revises: 
Create Date: 2026-05-15 22:39:26.780226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db7a04b5fc60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('squad_virtual_account_ref', sa.String(length=255), nullable=True),
    sa.Column('squad_customer_id', sa.String(length=255), nullable=True),
    sa.Column('squad_account_number', sa.String(length=20), nullable=True),
    sa.Column('squad_bank_name', sa.String(length=100), nullable=True),
    sa.Column('balance_naira', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_squad_customer_id'), 'clients', ['squad_customer_id'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_client_id'), 'api_keys', ['client_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('payment_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('amount_naira', sa.Integer(), nullable=False),
    sa.Column('payment_link', sa.Text(), nullable=False),
    sa.Column('squad_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_intents_client_id'), 'payment_intents', ['client_id'], unique=False)
    op.create_index(op.f('ix_payment_intents_squad_ref'), 'payment_intents', ['squad_ref'], unique=False)
    op.create_index(op.f('ix_payment_intents_status'), 'payment_intents', ['status'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('image_size_bytes', sa.Integer(), nullable=True),
    sa.Column('image_mime_type', sa.String(length=50), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('spatial_score', sa.Integer(), nullable=True),
    sa.Column('frequency_score', sa.Integer(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('billed_amount', sa.Integer(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('cache_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verifications_cache', 'verifications', ['image_hash', 'cache_expires_at'], unique=False, postgresql_where=sa.text('cached = false'))
    op.create_index('idx_verifications_created_at', 'verifications', [sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_verifications_client_id'), 'verifications', ['client_id'], unique=False)
    op.create_index(op.f('ix_verifications_image_hash'), 'verifications', ['image_hash'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('squad_ref', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('matched_client_id', sa.UUID(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matched_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_logs_matched', 'webhook_logs', ['matched'], unique=False, postgresql_where=sa.text('matched = false'))
    op.create_index('idx_webhook_logs_received_at', 'webhook_logs', [sa.text('received_at DESC')], unique=False)
    op.create_index(op.f('ix_webhook_logs_event_type'), 'webhook_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_logs_squad_ref'), 'webhook_logs', ['squad_ref'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=True),
    sa.Column('amount_naira', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('squad_ref', sa.String(length=255), nullable=True),
    sa.Column('squad_event', sa.String(length=50), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_created_at', 'transactions', [sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_transactions_client_id'), 'transactions', ['client_id'], unique=False)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_transactions_squad_ref'), 'transactions', ['squad_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_squad_ref'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_client_id'), table_name='transactions')
    op.drop_index('idx_transactions_created_at', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_webhook_logs_squad_ref'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_event_type'), table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_received_at', table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_matched', table_name='webhook_logs', postgresql_where=sa.text('matched = false'))
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_verifications_image_hash'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_client_id'), table_name='verifications')
    op.drop_index('idx_verifications_created_at', table_name='verifications')
    op.drop_index('idx_verifications_cache', table_name='verifications', postgresql_where=sa.text('cached = false'))
    op.drop_table('verifications')
    op.drop_index(op.f('ix_payment_intents_status'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_squad_ref'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_client_id'), table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_client_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_clients_squad_customer_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
